:toc: left

= Git

== Commits

commit `98ca9`:

- metadata (author, date, ...)
- previous commits
- tree `92ec2` (index snapshot)

tree `92ec2`:

- blob `5b1d3` README
- blob `911e7` LICENSE

objects:

- blob `5b1d3` README contents
- blob `911e7` LICENSE contents

=== Commit ranges

==== all commits in experiment not in master

 # all commits reachable from experiment that aren’t reachable from master
 git log master..experiment
 git log experiment --not master
 git log experiment ^master

==== what one is about to push to a remote

 git log origin/master..HEAD
 git log origin/master..

== Branches

`git branch -vv`

* a branch is a pointer to a commit
* `HEAD` points to the current branch # `git checkout br1` moves `HEAD->br1`
* The `HEAD` branch moves forward when a commit is made

`git ls-remote origin -> refs/heads/master # *heads* refers to 'branches'`

=== Track a remote(-tracking) branch (e.g origin/master)

you do that in order to use git pull/push without arguments (implied origin + remote)

note:: `origin/master` is called a remote-tracking branch.
       it's a local reference/pointer that can't be moved

 git checkout -b <branch> <remote>/<branch>
 git checkout --track origin/serverfix
 git checkout serverfix

 git branch -u origin/serverfix
 git push -u origin my-branch # set origin/my-branch (@{u[pstream]}) as upstream for my-branch
                    └─ or HEAD if on the branch

=== Prune remote-tracking branches

 git fetch --prune
 git remote prune origin

== Merge

 git checkout master
 git merge experiment

== Rebase
:sectnums:

=== rebase experiment onto master => experiment moves/points further ahead

`git rebase master experiment` + or

 git checkout experiment
 git rebase master

=== ff merge experiment into master => master catches up with experiment

 git checkout master
 git merge experiment

== diffs

=== diff

....
# difference between the tips of the branches
git diff foo..bar
git diff foo  bar

# changes introduced in bar, ignoring everything done on foo
git diff foo...bar
....

=== log

 git log A..B.  # commits in B that don't exist in A
 git log A...B. # commits in B that don't exist in A +
                  commits in A that don't exist in B

:sectnums!:
== Cherry Pick

Cherry picking is the act of picking a commit from a branch and applying it to another.

 a - b - c - d     main (current)
      \
       e - f - g   topic

 git cherry-pick f

 a - b - c - d - f main
      \
       e - f - g   topic

CAUTION:
*`f`* is now a duplicate commit. Only use if `topic` is not to be merged to `main` (i.e. we only need the single commit)

== Index aka staging area

Everything tracked is in your staging area - the index.

`git rm`::
    removes from both the index and the working copy

`git rm --cached`::
    removes from the index only => untracks the file!

=== redo last commit: change index plus/or commit message.

`git commit --amend`::
    same as:
    * `git reset --soft HEAD^`
    * modify staging area
    * `git commit`

_uncommit file example_::
    - `git reset @~ file`
    - `git commit --amend -m'...'`

== git reset

=== reset with a ref (commit) but without a path (file)

[.underline]#Our need is to change the commits...#

1. move the `HEAD->branch` pair to another commit.
2. update index: _stop here by default (change with --*soft*/*hard*)_
3. optionally update the working dir

HEAD (--soft)  ⇒  Index  ⇒  Working dir (--hard)

example 1: `git reset HEAD~`::
    * move `HEAD->branch` to previous commit => undo last commit
    * update index with the snapshot `HEAD->branch` points to => unstage everything

example 2: `git reset master`::
    * move `HEAD->branch` to where `master` points
    * ...

=== reset with a path (and optional commit)

1. [.underline]#Here, commit history isn't the issue, plus changing commit would affect many files => so skip this step#
2. unstage file or more accurately, copy file from HEAD to index

`git reset file`::
    unstage file (opposite of git add file)
`git reset`::
    unstage all files
`git reset --hard`::
    unstage everything + reset working dir

`git checkout master~2 file`::
    update the index + working dir from `master~2` commit (default is `HEAD`)
    `git reset --hard master~2 file` would do the same thing.

== reflog

* it's a *local* history of *all* (no history rewriting as with `git log`) commits
* ring buffer with a limited amount of data (a few months)

== git checkout

=== without paths

`git checkout [commit]`, same as +
`git reset --hard [commit]` but working-dir safe + only moves `HEAD`

=== with paths

`git checkout [commit] file`, same as +
`git reset --hard [commit] file` (but not implemented in `git-reset`)

=== create topic from local master and check it out
`git checkout -b topic master`

same as:

 git branch topic master
 git checkout topic

== refspec

- fetch = `+src(_remote_):dst(_local_)`
- push = `+src(_local_):dst(_remote_)`

`+`: update the reference even if it isn’t a fast-forward

remote branches `refs/heads/\*` go under `refs/remotes/origin/*` locally::
   `fetch = +refs/heads/\*:refs/remotes/origin/*`

_these are equivalent:_

 git push origin serverfix
 git push origin serverfix:serverfix
 git push origin refs/heads/serverfix:refs/heads/serverfix

=== delete remote reference

* `git push origin --delete topic`
* `git push origin :topic` <- push empty `src` to remote

== Operations in bulk

 fd --strip-cwd-prefix -FH -td .git | parallel --tag --tagstring '{//}' 'git -C {//} branch' | grep -v 'main$'
 fd --strip-cwd-prefix -FH -td .git | parallel --tag --tagstring '{//}' 'git -c color.status=always -C {//} status -sb'

== Configuration

=== store credentials for use with https

 git config --global credential.https://github.com.*username* kurkale6ka
 git config --global credential.helper store

then `git push` will ask for the token/password

== Glossary

parent commit of `HEAD`::
`HEAD^` or `HEAD~` or `@~`
