== Commits

commit 98ca9
- metadata (author, date, ...)
- previous commits
- tree 92ec2 (index snapshot)

tree 92ec2
- blob 5b1d3 README
- blob 911e7 LICENSE

objects
- blob 5b1d3 README contents
- blob 911e7 LICENSE contents

=== Commit ranges

==== all commits in experiment not in master

 # all commits reachable from experiment that aren’t reachable from master
 git log master..experiment
 git log experiment --not master
 git log experiment ^master

==== what one is about to push to a remote

 git log origin/master..HEAD
 git log origin/master..

== Branches

`git branch -vv`

a branch is a pointer to a commit
HEAD points to the current branch # git checkout br1 moves HEAD to br1
The HEAD branch moves forward when a commit is made

git ls-remote origin -> refs/heads/master # heads refers to 'branches'

== Track a remote(-tracking) branch (e.g origin/master)

you do that in order to use git pull/push without arguments (implied origin + remote)

note:: origin/master is called a remote-tracking branch.
       it's a local reference/pointer that can't be moved

 git checkout -b <branch> <remote>/<branch>
 git checkout --track origin/serverfix
 git checkout serverfix

 git branch -u origin/serverfix
 git push -u origin my-branch # set origin/my-branch (@{u[pstream]}) as upstream for my-branch

 git push origin serverfix
 git push origin serverfix:serverfix
 git push origin refs/heads/serverfix:refs/heads/serverfix

== Index aka staging area

Everything tracked is in your staging area - the index.

git rm
------
    removes from both the index and the working copy

`git rm --cached`
    removes from the index only => untracks the file!

`git commit --amend`::
redo last commit: change index plus/or commit message.
same as:
* `git reset --soft HEAD^`
* modify staging area
* `git commit`

_uncommit file example:_

- `git reset HEAD~ file`
- `git commit --amend -m'...'`

== git reset

=== reset with a ref (commit) but without a path (file)

[.underline]#Our need is to change the commits...#

1. move `HEAD->branch` to another commit.
2. update index: _stop here by default (change with --*soft*/*hard*)_
3. optionally update the working dir

HEAD (--soft)  ⇒  Index  ⇒  Working dir (--hard)

example 1: `git reset HEAD~`::
    * move `HEAD->branch` to previous commit => undo last commit
    * update index with the snapshot `HEAD->branch` points to => unstage everything

example 2: `git reset master`::
    * move `HEAD->branch` to where `master` points
    * ...

=== reset with a path (and optional commit)

1. [.underline]#Here, commit history isn't the issue, plus changing commit would affect many files => so skip this step#
2. unstage file or more accurately, copy file from HEAD to index

git reset file::
    unstage file (opposite of git add file)
git reset::
    unstage all files
git reset --hard::
    unstage everything + reset working dir

git checkout master~2 file::
    update the index + working dir from `master~2` commit (default is `HEAD`)
    `git reset --hard [branch] file` would do the same thing.

== reflog

* it's a *local* history of *all* (no history rewriting as with `git log`) commits
* ring buffer with a limited amount of data (a few months)

git rebase
----------
git rebase -i HEAD~5 # interactive

git add
-------
git add -p # only add chosen hunks for this commit

git checkout
------------
git checkout -b topic master
git branch topic master && git checkout topic
    create topic from local master and check it out

git push
--------
git push origin serverfix
git push origin serverfix:serverfix
git push origin refs/heads/serverfix:refs/heads/serverfix
                               local:remote

After a git fetch that brings origin/serverfix (upstream or @{u}),
is git checkout -b serverfix origin/serverfix equivalent to
   git checkout --track origin/serverfix
   git checkout serverfix

Those create a tracking branch => git pull knows what server/branch to pull from

Set current branch to track:
    git branch -u origin/serverfix

Rename a branch
---------------
git branch -m new
git push origin :old   # delete the remote branch
git push -u origin new # push and track the new branch

Make an existing Git branch track a remote branch
-------------------------------------------------

git branch -u origin/foo

== Annexe

HEAD~ is the same as HEAD^ which is the parent commit of HEAD
