= Variables

Variables are pointing to objects and objects can be of arbitrary data type,
thus variables cannot have types associated with them

x = 11, y = x => id(x) == id(y) (x is y)

= Quotes
' and " are equivalent
variable interpolation: f'Hello {var}' or 'Hello {}'.format(var)

= Tips
In interactive mode, the last printed expression is assigned to _

whenever a list needs to be created/shortened in a loop (e.g with .append()/.remove()),
assess if using a comprehension wouldn't be easier/clearer

str.index (raises ValueError) <~>
str.find (returns -1)

if 'yellow' in colors: # shorter/easier than
any(c == 'yellow' for c in colors)

(... for t in text if t.isalpha()) # could lead to a better solution than using
filter(str.isalpha, text)

Turn a list into a string with str(ls) vs
''.join(str(i) for i in ls) # not exactly the same but maybe ok

return a > b # just return the boolean expression
return True if a > b else False # True if True False if False :-)

zip('abs', '@&$') # strings are sequences
zip(['a', 'b', 's'], ['@', '&', '$'])

  packing: assign to *t, we get a single tuple
unpacking:       use *t, we get all items

= Decorators
Pass my function to a 'decorator' function, so it can apply it AND add extra
functionality, then return a new function to replace my initial one:

my_func = decorator(my_func) # which is what happens with:

@decorator
my_func(...)

= Iterators

- iterables implement __iter__ to return an iterator
- an iterator implements __next__ to get elements + raises StopIteration
- a generator helps to create an iterator thanks to the yield statement

(n**2 for n in seq) generator expression:
* create items as needed => little RAM, infinite sequences
* iterate once, no access to list methods

[n**2 for n in seq] list comprehension:
create whole list in RAM

islice() parameters act similarly to range()'s ones,
the difference is we get an iterator, not a range.

groupby(iterable, key=None) # define a key per item (identity by default)
(key1, iterator1), ..., (keyN, iteratorN)

operator.itemgetter(0) is the same as lambda g: g[0]

= Regex

== use match.group() after a match:

    match(^pattern , string, flags=0) -> match
fullmatch(^pattern$, string, flags=0) -> match
   search( pattern , string, flags=0) -> match

findall(pattern, string, flags=0) -> list/list of groups

split(pattern, string, maxsplit=0, flags=0) -> list/list of groups

# s///
sub(pattern, repl, string, count=0, flags=0) -> string

with pattern:
1. compile(pattern, flags=0) -> pattern
2. pattern.match(string) for example

= Virtual environments

venv: create isolated working copies of python with their own site packages.
This solves the problem of various python projects needing different versions
of the same 3rd party packages (aka site packages).

* python3 -mvenv neovim
* source neovim/bin/activate
* pip install --upgrade pip
* pip install --upgrade pynvim
* deactivate

system wide python installation:
sudo pip install

isolated python installation:
pip install --user # without venv
pip install        # if using venv
