:toc: left

= Terraform

== State

`terraform 'refresh'` checks if objects in my 'real world' (state file) exist and are the same in the actual world (_e.g_ cloud). +
Thus, if I `terraform state rm ADDR`, I've got less things to compare => +
a `'refresh'` on an empty state would report 'No changes' (_nothing to compare_)!

== HCL (HashiCorp Configuration Language)

=== Syntax

 blk_type "label1" ... "labeln" {
    # argument
    name = "value"
 }

 terraform {
    required_providers {
       aws = {
          source = registry.terraform.io/hashicorp/aws ...

remote registry:: [hostname]/namespace/name/provider//subdir

`provider "aws" { ...`

`resource "aws_instance (*type*)" "app_server (*name*)" {`

id:: aws_instance.app_server

`for_each` = `map` or `set` => `each.key` [+ `each.value`]

== Data sources

Resources take arguments and export attributes for use in configuration, but
while managed resources cause Terraform to create, update, and delete
infrastructure objects, data resources cause Terraform only to read objects

== Modules

folder with _.tf_ files in it

 +-- elasticache/
 ¦   +-- main.tf
 ¦   ¦   # resource "aws_elasticache_replication_group" "elasticache-cluster" {
 ¦   ¦   #   replication_group_id = "tf-${var.environment}-rep-group"
 ¦   ¦   #   availability_zones   = ["${var.availability_zones}"]
 ¦   +-- variables.tf
 ¦       # variable "environment" {}
 ¦       # variable "availability_zones" { type = "list" }
 +-- environments/
 ¦   +-- production/
 ¦   ¦   +-- main.tf
 ¦   ¦       # module "prod-elasticache" {
 ¦   ¦       #   source = "../../elasticache"
 ¦   ¦       #   environment        = "dev"
 ¦   ¦       #   availability_zones = ["us-east-1a", "us-east-1b"]
 ¦   +-- staging/
 ¦       +-- main.tf
 ¦           # module "stg-elasticache" {
 ¦           #   source = "../../elasticache"
 +-- main.tf
     # module "production" {
     #   source = "environments/production"
     # }

== Deprecated

* `terraform [.line-through]#taint#` vs `terraform apply -replace aws_instance.web1`
* `terraform [.line-through]#refresh#` vs `terraform apply -refresh-only`
