:toc: left

= Terraform

== Command Line

 terraform init       # install provider plugins in .terraform
 terraform plan       # preview changes
 terraform apply      # apply changes
 terraform show       # inspect state
 terraform state list
 terraform validate   # config check
 terraform fmt        # coding standards

== HCL (HashiCorp Configuration Language)

=== Syntax

 blk_type "label1" ... "labeln" {
    # argument
    name = "value"
 }

 terraform {
    required_providers {
       aws = {
          source = registry.terraform.io/hashicorp/aws ...

remote registry:: [hostname]/namespace/name/provider//subdir

`provider "aws" { ...`

`resource "aws_instance (*type*)" "app_server (*name*)" {`

id:: aws_instance.app_server

== Modules

folder with _.tf_ files in it

 +-- elasticache/
 ¦   +-- main.tf
 ¦   ¦   # resource "aws_elasticache_replication_group" "elasticache-cluster" {
 ¦   ¦   #   replication_group_id = "tf-${var.environment}-rep-group"
 ¦   ¦   #   availability_zones   = ["${var.availability_zones}"]
 ¦   +-- variables.tf
 ¦       # variable "environment" {}
 ¦       # variable "availability_zones" { type = "list" }
 +-- environments/
 ¦   +-- production/
 ¦   ¦   +-- main.tf
 ¦   ¦       # module "prod-elasticache" {
 ¦   ¦       #   source = "../../elasticache"
 ¦   ¦       #   environment        = "dev"
 ¦   ¦       #   availability_zones = ["us-east-1a", "us-east-1b"]
 ¦   +-- staging/
 ¦       +-- main.tf
 ¦           # module "stg-elasticache" {
 ¦           #   source = "../../elasticache"
 +-- main.tf
     # module "production" {
     #   source = "environments/production"
     # }

== Deprecated

* `terraform [.line-through]#taint#` vs `terraform apply -replace aws_instance.web1`
* `terraform [.line-through]#refresh#` vs `terraform apply -refresh-only`
